### ISSUE TITLE
Add deploy platform

### ISSUE THREAD

**Issue by JuanVqz** [JuanVqz/swapi#3]
Right now we have several FREE options that we can choose from:

- https://render.com/
- https://vercel.com/
- Heroku
- digital ocean
- Netlify
- GitHub Pages

Have you used any of them?

I have seen Vercel has a preview when somebody opens a PR, that feature makes me think it's a good option to go, but I don't know what the other alternative offer

**Comment by Vallejoanderson** [comment]
Been using Netlify but I'm quite interested in Vercel or Heroku.

**Comment by JuanVqz** [comment]
> Been using Netlify but I'm quite interested in Vercel or Heroku.

I have used Heroku a lot but I don't want to use it this time here.
(for rails applications it is awesome/easy all good about it so far)

Let's wait for @davbrito suggestions/interests.

BTW, you are always welcome to contribute here, don't be afraid of adding something wrong, we will help if we know you can improve, let's tackle it!

**Comment by davbrito** [comment]
My suggestion is to use Vercel. It's very easy to deploy and it generates automatic preview deploys for every push to a branch or PRs.

I've used also CloudFlare Pages and it offers similar benefits to Vercel. 

I don't think Heroku is a good choice for this page.

**Comment by JuanVqz** [comment]
if Cloudflare pages offer the preview feature, my vote is for it, since I haven't used it and I'd like to know more about it.

okay, next, meeting let's see if we can put this on production.

**Comment by JuanVqz** [comment]
This issue has been done, at the end we added Vercel, it allows us to see a preview per PR.
